
services:
  postgresdb:
    image: timescale/timescaledb:latest-pg13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  traccar:
    image: traccar/traccar:6-ubuntu
    depends_on:
      - postgresdb
    restart: always
    ports:
      - 8082:8082
      - 5055:5055
      #- 5000-5150:5000-5150
    volumes:
        - ./traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro
        - ./traccar/logs:/opt/traccar/logs

  benthos:
    # image: ci4rail/redpanda-connect-kyt:v1.2.0
    image: ci4rail/redpanda-connect-kyt:vtest
    depends_on:
      - traccar
    command:
      - "-c"
      - "/config/benthos-chemnitz.yaml"
    restart: always
    ports:
      - 11001:11001/udp
      - 4195:4195
    volumes:
        - ./benthos-io4edge:/config:ro
        - ./benthos-io4edge/logs:/root/logs:rw

  prometheus:
    image: prom/prometheus:v2.53.5
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=120d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana-enterprise:11.6.5
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=ci4rail
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana


volumes:
  grafana_data:
  prom_data:
  postgres-data:
