
services:
  postgresdb:
    image: timescale/timescaledb:latest-pg13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  traccar:
    image: traccar/traccar:6-ubuntu
    depends_on:
      - postgresdb
    restart: always
    ports:
      - 8082:8082
      - 5055:5055
      #- 5000-5150:5000-5150
    volumes:
        - ./traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro
        - ./traccar/logs:/opt/traccar/logs

  benthos:
    image: ci4rail/redpanda-connect-kyt:v2.1.0-rc.1
    depends_on:
      - traccar
    command:
      - "-c"
      - "/config/benthos-config.yaml"
    restart: always
    environment:
      EASYPLAN_IP: <EasyplanIP>
      EASYPLAN_PORT: <EasyplanPort>
      ORIGIN_LAT: 49.43073532167714
      ORIGIN_LON: 11.070874949779965
      ORIGIN_AZI: 346.21484763670827
    ports:
      - 11001:11001/udp
      - 4195:4195
    volumes:
        - ./benthos-io4edge:/config:ro
        - ./benthos-io4edge/logs:/root/logs:rw

  prometheus:
    image: prom/prometheus:v2.53.5
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=120d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana-enterprise:11.6.5
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=ci4rail
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

  alloy:
    image: grafana/alloy:v1.2.1
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/store
      - /config/config.alloy
    working_dir: /config
    volumes:
      - ./alloy:/config
      - alloy-data:/store
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /run/udev/data:/host/run/udev/data:ro
    # enable only for debugging
    # ports:
    #   - "12345:12345"
    restart: unless-stopped
    pid: host
    network_mode: host


volumes:
  grafana_data:
  prom_data:
  postgres-data:
  alloy-data:
